const fs = require("node:fs");
const path = require("node:path");

/* global __dirname */

// 🔧 ANPASSEN
const ASSETS_DIR = path.resolve(__dirname, "../assets/images/quiz");
const OUTPUT_FILE = path.resolve(
  __dirname,
  "../src/assets/quizImages.ts"
);

// Erlaubte Bildformate
const VALID_EXTENSIONS = [".png", ".jpg", ".jpeg", ".webp"];

/**
 * Normalisiert Strings → Asset-Key
 * MUSS identisch zur Runtime-Funktion sein!
 */
function normalizeKey(value) {
  return value
    .toLowerCase()
    .replace(/ä/g, "ae")
    .replace(/ö/g, "oe")
    .replace(/ü/g, "ue")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/**
 * Rekursiv alle Bilder einsammeln
 * Region = erster Ordner unter /quiz
 */
function collectImages(dir, baseDir = dir, region = null, acc = []) {
  const items = fs.readdirSync(dir, { withFileTypes: true });

  for (const item of items) {
    const fullPath = path.join(dir, item.name);

    if (item.isDirectory()) {
      const nextRegion = region ?? item.name;
      collectImages(fullPath, baseDir, nextRegion, acc);
      continue;
    }

    if (!VALID_EXTENSIONS.includes(path.extname(item.name))) {
      continue;
    }

    acc.push({
      region,
      fileName: path.basename(item.name, path.extname(item.name)),
      relativePath: path.relative(baseDir, fullPath).replace(/\\/g, "/"),
    });
  }

  return acc;
}

const images = collectImages(ASSETS_DIR);

const entries = images.map(({ region, fileName, relativePath }) => {
  if (!region) {
    throw new Error(
      `❌ Bild liegt nicht in einem Regions-Ordner: ${relativePath}`
    );
  }

  const key = `${normalizeKey(region)}_${normalizeKey(fileName)}`;

  return `  ${key}: require("@/assets/images/quiz/${relativePath}"),`;
});

const content = `// ⚠️ AUTO-GENERATED FILE – DO NOT EDIT
// Generated by scripts/generateQuizImageAssets.js

export const quizImageAssets: Record<string, number> = {
${entries.join("\n")}
};
`;

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, content);

console.log("✅ quizImages.ts generated with", entries.length, "entries");
